### ISSUE TITLE
[User Story]: CommonMark Posts

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#11]
### User Story

As an author, posts I make can be in CommonMark.

### Objects

Single Author, Post

**Comment by giancarlopernudisegura** [comment]
Here is the [CommonMark website](https://commonmark.org/). It's essentially markdown.

**Comment by giancarlopernudisegura** [comment]
https://www.npmjs.com/package/commonmark

**Comment by dellahumanita** [comment]
- [ ] Meet with Lidia to discuss TypeScript 4
- [ ] Integrate CommonMark
- [ ] Check that pictures can be added by drag-and-drop 
- [ ] Check that markdown annotations could work
- [ ] Create a Preview tab (like Github)
