### ISSUE TITLE
[User Story]: Delete Posts

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#17]
### User Story

As an author, I want to delete my own public posts.

### Objects

Single Author, Post

**Comment by dellahumanita** [comment]
- [x] Add a delete button on the PostForm 
- [x] Make a DELETE request 
- [x] Test that it works

**Comment by dellahumanita** [comment]
https://www.robinwieruch.de/react-remove-item-from-list/
