### ISSUE TITLE
[User Story]: Manage Profile

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#24]
### User Story

As an author, I want to be able to use my web browser to manage my profile.

### Objects

Single Author

**Comment by dellahumanita** [comment]
- [x] Create the paths in `web.py` and `app.tsx`
- [x] Display my own posts 
- [x] Display image and displayName
- [ ] Create post on my own profile
- [ ] Edit posts
- [ ] Toggle visibility of posts (public or to another author)
- [x] List number of Followers and Following
 
Nice to have:
- [ ] Create modal of Followers list
- [ ] Create modal of Followers list
