### ISSUE TITLE
[User Story]: Follower vs Friends

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#35]
### User Story

As an author, when I befriend someone, I follow them. Only when the other author befriends me do I count as a real friend – a bi-directional follow is a true friend.

### Objects

Followers, Friend/Follow Request

**Comment by dellahumanita** [comment]
Assume current author is Alice and another author is Becky. 
They are strangers (Alice does not follow Becky and Becky does not follow Alice)

- Alice searches for another author
- Identify relationship of Alice with Becky 
- Alice can follow Becky if they are not following already 
- Becky accepts Alice's follow request => Alice becomes Becky's follower
- (to become friends) Becky sends Alice a follow request 
- Alice accepts Becky's request => Alice follows Becky AND Becky follows Alice => they are friends

**Becoming a follower of another author**
- [x] Get a list of multiple authors (search or list of authors)
- [x] Select an author that you are not following
- [x] Send a follow request

**Comment by dellahumanita** [comment]
**Pagination Issues**

- When you get to the end of the list, it returns a 404 error

**Comment by dellahumanita** [comment]
Update: Completed friend functionality in the Profile page. 
Blockers:
- API endpoint returning the information about the author in the 'to' column
- Current implementation is tightly coupled in the Profile, relying on chained promises. I am finding it difficult to refactor the friends into its own function

Next actions:
- Implement a similar function in UserPage
- Obtain the list of friends and followers to be viewable by the author
