### ISSUE TITLE
[User Story]: Browse Public Posts

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#37]
### User Story

As an author, I should be able to browse the public posts of everyone.

### Objects

Post, Inbox

**Comment by dellahumanita** [comment]
TODO 
- [x] Create Post with title, author, date and body
- [x] Create List of Posts 
- [x] Create Explore page 
- [x] Add dummy public posts to the database
- [x] Display dummy public posts

**Comment by dellahumanita** [comment]
Resolving `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded` from 
```
File "/home/della/year4/404/social-distribution/cmput404/server/models.py", line 41, in json
    resp = urlopen(f"https://api.github.com/user/{self.githubId}")
```

- An unauthenticated user has a rate limit of 60. 
- A temporary solution for now is to hardcode my github authetication

**Comment by dellahumanita** [comment]
Resolving `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded` from 
```
File "/home/della/year4/404/social-distribution/cmput404/server/models.py", line 41, in json
    resp = urlopen(f"https://api.github.com/user/{self.githubId}")
```

- An unauthenticated user has a rate limit of 60. 
- A temporary solution for now is to hardcode my github authentication

**Comment by dellahumanita** [comment]
- [x] Create tabs for Github stream and Public Posts
- [x] Ensure that Posts are all public
- [x] Add pagination
