### ISSUE TITLE
[User Story]: Add Nodes

### ISSUE THREAD

**Issue by giancarlopernudisegura** [giancarlopernudisegura/cmput404#38]
### User Story

As a server admin, I want to be able to add nodes to share with.

### Objects

Inbox

**Comment by dellahumanita** [comment]
- [ ] Differentiate between local and remote IDs
- [ ] Identify remote team 1 URLs
- [ ] Identify remote team 2 URLs
- [ ] Refactor `apiCalls.tsx` to accept local and remote URLs
